# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Exam.create(id:1, name:"実用タイ語検定試験", language:"タイ語", event_date:"2020-06-07", event_status:"開催前")
ExamGrade.create(exam_id:1, grade:"5級")
QuestionField.create(id:1, name:"穴埋め", question_description:"次の（ ）内に入れるのに最も適当な語を選びその番号をマークしなさい。")
Question.create(id:1, exam_grade_id:1, number:1, question_field_id:1, sentence_short:"(    )点以上が合格になります。")
QuestionAnswer.create(id:1, question_id:1, choice_number:1, sentence:"60", correct_flg:false)
QuestionAnswer.create(id:2, question_id:1, choice_number:2, sentence:"70", correct_flg:false)
QuestionAnswer.create(id:3, question_id:1, choice_number:3, sentence:"80", correct_flg:true)
QuestionAnswer.create(id:4, question_id:1, choice_number:4, sentence:"90", correct_flg:false)
QuestionSetType.create(id:1, name:"級選択")
QuestionSetType.create(id:2, name:"年度選択")
QuestionSetType.create(id:3, name:"分野選択")
QuestionSetType.create(id:4, name:"出題順序選択")
QuestionSetType.create(id:5, name:"オプション選択")
QuestionSetValue.create(id:1, question_set_type_id:1, name:"5級")
QuestionSetValue.create(id:2, question_set_type_id:1, name:"4級")
QuestionSetValue.create(id:3, question_set_type_id:1, name:"3級")
QuestionSetValue.create(id:4, question_set_type_id:1, name:"準2級")
QuestionSetValue.create(id:5, question_set_type_id:1, name:"2級")
QuestionSetValue.create(id:6, question_set_type_id:1, name:"1級")
QuestionSetValue.create(id:7, question_set_type_id:2, name:"2020年春季")
QuestionSetValue.create(id:8, question_set_type_id:2, name:"2019年秋季")
QuestionSetValue.create(id:9, question_set_type_id:2, name:"2019年春季")
QuestionSetValue.create(id:10, question_set_type_id:2, name:"2018年秋季")
QuestionSetValue.create(id:11, question_set_type_id:2, name:"2018年春季")
QuestionSetValue.create(id:12, question_set_type_id:2, name:"2017年秋季")
QuestionSetValue.create(id:13, question_set_type_id:2, name:"2017年春季")
QuestionSetValue.create(id:14, question_set_type_id:2, name:"2016年秋季")
QuestionSetValue.create(id:15, question_set_type_id:2, name:"2016年春季")
QuestionSetValue.create(id:16, question_set_type_id:2, name:"2015年秋季")
QuestionSetValue.create(id:17, question_set_type_id:2, name:"2015年春季")
QuestionSetValue.create(id:18, question_set_type_id:2, name:"2014年秋季")
QuestionSetValue.create(id:19, question_set_type_id:3, name:"穴埋め")
QuestionSetValue.create(id:20, question_set_type_id:4, name:"標準")
QuestionSetValue.create(id:21, question_set_type_id:4, name:"ランダム")
QuestionSetValue.create(id:22, question_set_type_id:4, name:"正答率の高い順")
QuestionSetValue.create(id:23, question_set_type_id:4, name:"正答率の低い順")
QuestionSetValue.create(id:24, question_set_type_id:5, name:"未解答問題のみ")
QuestionSetValue.create(id:25, question_set_type_id:5, name:"選択肢を並び替える")
QuestionSetValue.create(id:26, question_set_type_id:5, name:"解説が無い問題は出題しない")
QuestionSetValue.create(id:27, question_set_type_id:5, name:"出題数を指定する")